spring.config.activate.on-profile: local
kdt:
  version: "local-v1.0"
  path:
    voucher-list: "/kdt-spring-order/src/main/resources/.csv/voucher_list.csv"
    customer-blacklist: "/kdt-spring-order/src/main/resources/.csv/customer_blacklist.csv"