spring.config.activate.on-profile: dev

kdt:
  version: "v1.0.0-dev"
  minimum-order-amount: 1
  support-vendors:
    - deva
    - devb
    - devc
    - devd
  description: |
    line 1 hello world dev
    line 2 xxxxx dev
    line 3 dev