logging:
  level:
    root: warn

kdt:
  version: "v1.0.0"
  minimum-order-amount: 1
  support-vendors:
    - a
    - b
    - c
    - d
  description: |
    line 1 hello world
    line 2 xxxxx
    line 3

spring:
  profiles.active: dev

db_path:
 txt_path: "db.txt"
 csv_path: "customer_blacklist.csv"