spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost/order_mgmt
    username: root
    password: root1234

csv:
  file-path : /src/main/resources/csv/
  voucher-repository:
    file-name : voucher_list.csv
  customer-blacklist:
    file-name : customer_blacklist.csv
