#logging:
#  level:
#    root: warn
# 파일을 나눠서 해도 된다.
servers:
  - dev.bar.com
  - foo.bar.com
  -
---

spring.config.activate.on-profile: local   # 이것은 spring boot에서 지원하므로 spring에서는 지원하지 않는 기능.!
kdt:
  version: "v1.0"
  minimum-order-amount: 1


---
spring.config.activate.on-profile: dev
kdt:
  version: "v1.0"
  minimum-order-amount: 1


