spring.config.activate.on-profile: memory

---

spring.config.activate.on-profile: csv

csv:
  file-path : /src/main/resources/csv/
  voucher-repository:
    file-name : voucher_list.csv
  customer-blacklist:
    file-name : customer_blacklist.csv

---

#spring.config.activate.on-profile: jdbc
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost/order_mgmt
#    username: root
#    password: root1234




