kdt:
  version: "v1.0"
  minimum-order-amount: 1
  support-vendors:
    - a
    - b
    - c
    - d
    - e
  description: |
    line 1 hello world
    line 2 xxxx
    line 3

file:
  voucher-name: "voucher_file.txt"
  customer-name: "customer_blacklist.csv"
