spring:
  profiles:
    active: dev

file:
  voucher:
    path: "src/main/resources/csv/file-voucher-list.csv"
  member:
    blacklist:
      path: "src/main/resources/csv/customer-blacklist.csv"