# default

spring:
  datasource:
    url: jdbc:mysql://localhost/order_mgmt
    username: root
    password: root1234
  thymeleaf:
    prefix: "/WEB-INF/"
    view-names: "views/*"


---

spring.config.activate.on-profile: memory

---

spring.config.activate.on-profile: csv

csv:
  file-path : /src/main/resources/csv/
  voucher-repository:
    file-name : voucher_list.csv
  customer-blacklist:
    file-name : customer_blacklist.csv






