
servers:
  - dev.bar.com
  - foo.bar.com
  -
---

spring.config.activate.on-profile: local   # 이것은 spring boot에서 지원하므로 spring에서는 지원하지 않는 기능.!
kdt:
  version: "v1.0"
  minimum-order-amount: 1
  support-vendors: # List는 configuration propertys써야함
    - a
    - b
    - c
    - d
  description: |- # -는 포함시킴
    line 1 hello world
    line 2 xxxx
    line 3

---
spring.config.activate.on-profile: dev
kdt:
  version: "v1.0"
  minimum-order-amount: 1
  support-vendors: # List는 configuration propertys써야함
    - dev-a
    - dev-b
    - dev-c
    - dev-d
  description: |- # -는 포함시킴
    dev line 1 hello world
    dev line 2 xxxx
    dev line 3

