spring.config.activate.on-profile: dev
kdt:
  version: v1.0-dev
  description: |-
    dev profile
  file:
    black-list:
      path: customer_blakcklist.csv

---

spring.config.activate.on-profile: prod
kdt:
  version: v1.0-prod
  description: |- #-에 따라 마지막 줄마꿈이 포함되거나 안포함된다. -있으면 안포함
    prod profile
  file:
    black-list:
      path: customer_blakcklist.csv
    voucher-storage:
      path: voucher_data.ser