spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_mgmt?characterEncoding=utf8&serverTimezone=UTC
    username: kdt
    password: kdt
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    view-names: "views/*"
    prefix: "/WEB-INF/"
  sql:
    init:
      mode: always
      data-locations: classpath:schema.sql, data.sql
      platform: mysql

server:
  servlet:
    context-path: /kdt

logging:
  level:
    root: info
    web: debug
    org:
      prgrms:
        kdt: debug
    sql: debug

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
