servers:
  - dev.bar.com
  - foo.bar.com

---

spring.config.activate.on-profile: local

kdt:
  version: "v1.0"
  minimum-order-amount: 1
  support-vendors:
    - a
    - b
    - c
    - d
  description: |- # - 기호가 있으면 마지막에 줄 바꿈 포함 X
    line 1 hello world
    line 2 xxx

---

spring.config.activate.on-profile: dev

kdt:
  version: "v1.0 dev"
  minimum-order-amount: 1
  support-vendors:
    - a dev
    - b dev
    - c dev
    - d dev
  description: |- # - 기호가 있으면 마지막에 줄 바꿈 포함 X
    line 1 hello world dev
    line 2 xxx dev

---
