spring:
  profiles:
    source: production
data:
  customer:
    path: ./
    name: customer.csv
kdrt:
  version: "v1.0-local"
  minimum-order-amount: 0
  support-vendors:
    - a
  description: |-
    line 1