spring:
  datasource:
    url: jdbc:mysql://localhost/order_mgmt
    username: root
    password: root1234!
  thymeleaf:
    view-names: "views/*"
    prefix: "/WEB-INF/"
server:
  servlet:
    context-path: /kdt

logging:
  level:
    org:
      springframework: INFO


app:
  version: 1.0.0
  file:
    blackList: "customer_blacklist.csv"
    voucher: "voucher.txt"
