kdt:
  version: v1.0.0
  description: |-
    defualt profile
  file:
    black-list:
      path: data/customer_blacklist.csv

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/command_application
    username: root
    password: root1234!
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix : .html
    cache : false