spring:
  profiles:
    active: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devcourse_springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false
    username: devcourse
    password: devcourse
customer:
  blacklist:
    file-path: file:customer/
    file-name: customer_blacklist.csv