kdt:
  version: v1.0.0
  description: |-
    defualt profile
  file:
    black-list:
      path: data/customer_blacklist.csv

spring:
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix : .html
    cache : false