spring:
  datasource:
    url: "jdbc:mysql://localhost/order_mgmt"
    username: "root"
    password: "root1234!"
data:
  storage:
    name: memoryVoucherRepository
  description: |-
    profile : dev