spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/voucher_order_mgmt"
    username: root
    password: root1234!
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
  thymeleaf:
    view-names: "views/*"
    prefix: "/WEB-INF/"
server:
  servlet:
    context-path: /kdt
kdt:
  version: "dev property"
  file:
    voucher-name: "voucher_file.txt"
    customer-name: "customer_blacklist.csv"

