spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: "jdbc:mysql://localhost:3306/voucher_order_mgmt"
    username: root
    password: root1234!
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50


kdt:
  version: "dev property"
  file:
    voucher-name: "voucher_file.txt"
    customer-name: "customer_blacklist.csv"

