data:
  voucher-storage:
    prefix: data
    name: storage.tmp
  customer-blacklist:
    prefix: data
    name: customer_blacklist.csv

spring:
  profiles:
    active: prod

---
spring:
  config:
    activate:
      on-profile: test

data:
  voucher-storage:
    prefix: data
    name: storage-test.tmp
