spring:
  datasource:
    url: jdbc:mysql://localhost/order_mgmt
    username: root
    password: 1234
  thymeleaf:
    view-names: "views/*"
    prefix: "/WEB-INF/"
    encoding: UTF-8
server:
  servlet:
    context-path: /kdt_spring_order_war_exploded
logging:
  level:
    org:
      springframework: DEBUG